[package]
name = "gylo-redis"
version = "0.1.0"
edition = "2024"
license.workspace = true
description = "Redis backend for gylo"
repository.workspace = true

[dependencies]
gylo-core.workspace = true
redis = { version = "1.5.0", features = ["tokio-comp", "script"] }
rmp-serde.workspace = true
serde.workspace = true
serde_bytes.workspace = true
thiserror.workspace = true
tokio.workspace = true
