[package]
name = "gylo-worker"
version = "0.1.0"
edition = "2024"
license.workspace = true
description = "Worker supervisor for gylo"
repository.workspace = true

[dependencies]
chrono.workspace = true
gylo-core.workspace = true
gylo-pg.workspace = true
metrics = "0.24.6"
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
rmp-serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["macros", "migrate"] }
