[package]
name = "gylo-pg"
version = "0.1.0"
edition = "2024"
license.workspace = true
description = "Postgres backend for gylo"
repository.workspace = true

[dependencies]
chrono.workspace = true
gylo-core.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["tls-rustls-ring", "uuid", "migrate", "macros", "json", "chrono"] }
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
